### ISSUE TITLE
Exporter running with user different from root

### ISSUE THREAD

**Issue by gunhu** [MindFlavor/prometheus_wireguard_exporter#27]
Hi,

I would really love to be able to run this exporter without the need to run it with root user.

Can I submit a PR in this way?

Regards,

**Comment by MindFlavor** [comment]
Yes of course! We accept any contribution: this is a open source project made for free by every contributor for the community (with ❤️)!

Just please note that, in order for me to pull your PR in, you must accept to surrender your code as per the [LICENSE](https://github.com/MindFlavor/prometheus_wireguard_exporter/blob/master/LICENSE) file.

**Comment by gunhu** [comment]
Perfect, I will submit a PR and surrender my code :)

**Comment by qdm12** [comment]
But is there a way to run `wg` without root? I'm interested as well regarding #39 it would be nice to run without root privileges.

**Comment by Thor77** [comment]
How about an option to prefix the wg-command with `sudo` so at least only the wireguard query has to run as root?

**Comment by MindFlavor** [comment]
> How about an option to prefix the wg-command with `sudo` so at least only the wireguard query has to run as root?

I'll try this although I think it will only work on passwordless sudo users.

**Comment by qdm12** [comment]
> How about an option to prefix the wg-command with sudo so at least only the wireguard query has to run as root?

I've done that for a development interactive container, but that doesn't really help for a service container. If someone gains access to the container it can run sudo which is pretty much the same as running as root.

Maybe there is a way to run wg without root or run some other commands giving the same information without root (like ip route etc.)?

**Comment by MindFlavor** [comment]
I've added the option in the aforementioned branch, please let me know what you think. 
Personally I agree with @qdm12: this workaround does not increase the security much. 

Let me know if you think it's worth merging or not :question: :question: :question:

**Comment by qdm12** [comment]
@MindFlavor You should at least add to the Dockerfile...

```Dockerfile
ARG USERNAME=user
ARG USER_UID=1000
ARG USER_GID=1000
RUN adduser $USERNAME -s /bin/sh -D -u $USER_UID $USER_GID && \
    mkdir -p /etc/sudoers.d && \
    echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME && \
    chmod 0440 /etc/sudoers.d/$USERNAME
```

To create a non root user and add it to the sudoers (can be at the start of the last image Dockerfile), and then at the end of the Dockerfile, set the user to that non root user

```Dockerfile
USER ${USERNAME}
```

And change your code to always run `wg` with `sudo`, as otherwise it won't work as you're not running as root.

A tiny security improvement, but really someone can just do `sudo rm -rf /*` in that case 😄

**Comment by MindFlavor** [comment]
Agreed but I would like to keep it a separate PR. I'll go on and merge this one because it doesn't do any harm. 

BTW @qdm12: since you are very active here, would you like to become a maintainer of this repo? This way you could help with dockers without being slowed down by my response time. (sorry for the thread hijack but GitHub does not allow direct messages)

**Comment by MindFlavor** [comment]
I'd like to keep this open until we have a complete solution.

**Comment by qdm12** [comment]
Yes, sure, thanks for asking! 😉 I'll make a PR for the Dockerfile

**Comment by qdm12** [comment]
By the way sorry about the Docker container focus, I forgot we can also run the app without a container 😅 
Although I would guess it's more of a host setup to do in that case, and not really relevant to the program.

@MindFlavor You might want to reset the commit on master because running with sudo doesn't add anything and `sudo` is sometimes not installed on some niche systems. I'll explore other options on how to set up a host system to run `wg` or other tools without root so that we could run the entire program (and container) without root.

**Comment by Thor77** [comment]
Thanks for implementing my suggestion, it works perfectly for my usecase (host-based deployment, running the exporter as a separate user).
I'm using this sudo rule: `prometheus-wireguard-exporter ALL=(root) NOPASSWD: /usr/bin/wg show * dump`

**Comment by MindFlavor** [comment]
> `prometheus-wireguard-exporter ALL=(root) NOPASSWD: /usr/bin/wg show * dump`

That's brilliant, thank you for sharing it :rocket: . I'll borrow it for my own deployment.

**Comment by qdm12** [comment]
@Thor77 your solution seems to fit the Docker image too, thanks for sharing! ([PR](https://github.com/MindFlavor/prometheus_wireguard_exporter/pull/49/files)). It actually does give a better security 😉  I'll eventually look if there is a way to run `wg` without root at all, but that may not be possible either.
