### ISSUE TITLE
graph from extras/png

### ISSUE THREAD

**Issue by jeepmullet** [MindFlavor/prometheus_wireguard_exporter#34]
Do you have a specific dashboard you're looking at in the screenshot? Do you mind sharing the json or linking to where you grabbed it?

Thank you

**Comment by MindFlavor** [comment]
Sure! Here is the version I'm using right now: [https://gist.github.com/MindFlavor/e5d678280e8c5c5bf16959bc9611cd49](https://gist.github.com/MindFlavor/e5d678280e8c5c5bf16959bc9611cd49). 
This one is slightly different from the screenshot because it renders the last handshake as a table instead of gauges. 

Maybe we should add more complex dashboards as part of the repo. I am not that skilled in Grafana but maybe someone else might chip in and help us. 
I am going to close this issue but please refer to the issue #35 for advancements on this topic!
